# Generated by Django 4.1.2 on 2022-10-29 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(default='+7', max_length=13)),
                ('login', models.CharField(default='', max_length=20)),
                ('password', models.CharField(default='', max_length=20)),
                ('name', models.CharField(default='', max_length=20)),
                ('birth', models.DateField()),
                ('tg', models.CharField(blank=True, default='@', max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
        ),
    ]
