# Generated by Django 4.1.2 on 2022-10-31 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration_Login', '0006_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tg',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
